const createCourseContent = async (req, res, next) => {};

deleteCourseContent();
updateCourseContent();
getAllCourseContent();
getCourseContent();
getSectionById();
addSection();
deleteSection();
updateSection();
getSection();
getTopic();
getTopicById();
deleteTopic();
updateTopic();
addTopic();
getLessonById();
getAllLessons();
deleteLesson();
updateLesson();
